### PR TITLE
Added a test case

### PR DESCRIPTION
**Pull request by krish777**
Added a test case to make sure I have configure the environment correctly or not.

### CODE REVIEW

**Comment by krish777** [comment]
Added a test case to make sure I have configure the environment correctly or not.

**Comment by judepayne** [comment]
Hello, what is the point of this test and the benefit to the project? It's looks to be a test that `:key` is not a d2 attribute and so an error should be thrown.

**Comment by judepayne** [comment]
ping @krish777

**Comment by judepayne** [comment]
Closing as can't see the value to the project

**Pull request closed without merging**
