### PR TITLE
Fixed line endings with normalization.

### PR DESCRIPTION
**Pull request by eddielao**
Test result for Windows 11.

Eddie@LZXTH1 MINGW64 ~/OneDrive/Dev/git/dictim (fix-line-ends)
$ clj -X:test

Running tests in #{"test"}

Testing dictim.d2.compile-test

Testing dictim.d2.parse-test

Testing dictim.flat-test

Testing dictim.graphspec-test

Testing dictim.json-test

Testing dictim.template-test

Ran 83 tests containing 361 assertions.
0 failures, 0 errors.

Eddie@LZXTH1 MINGW64 ~/OneDrive/Dev/git/dictim (fix-line-ends)

### CODE REVIEW

**Comment by judepayne** [comment]
I will accept this PR - thank you.
One change to make. Can you make the new function private to the namespace please?

**Comment by eddielao** [comment]
> I will accept this PR - thank you. One change to make. Can you make the new function private to the namespace please?

Hi @judepayne , thank you for the suggestion! Change made and reran the test.

$ git commit -m "Made normalize-line-endings function private."
[fix-line-ends af109e9] Made normalize-line-endings function private.
 1 file changed, 1 insertion(+), 1 deletion(-)

$ clj -X:test

Running tests in #{"test"}

Testing dictim.d2.compile-test

Testing dictim.d2.parse-test

Testing dictim.flat-test

Testing dictim.graphspec-test

Testing dictim.json-test

Testing dictim.template-test

Ran 83 tests containing 361 assertions.
0 failures, 0 errors.

**Comment by judepayne** [comment]
Thankyou! Merged and re-pushed

**Comment by judepayne** [comment]
BTW, please see my comment to you here: https://github.com/judepayne/dictim/issues/3

**Pull request merged**
